[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cached = "43ffbea4-38f1-43a5-9bfb-671206d3a474"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DemoPlots = "1f342d77-e470-4fee-b19c-8e8d164daffc"
HetDister = "50651ce3-0423-45d2-b99c-8ea4267d2717"
HistogramBinnings = "8296b526-8b84-45d3-81d6-36727ca56808"
MariuxUtils = "be701e70-f25e-4246-ad85-09b5c637c424"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
